name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  miri:
    uses: taiki-e/github-actions/.github/workflows/miri.yml@a57add62f2464b6791c594783f513e5194350ac9 # main
  msrv:
    uses: taiki-e/github-actions/.github/workflows/msrv.yml@a57add62f2464b6791c594783f513e5194350ac9 # main
  test:
    uses: taiki-e/github-actions/.github/workflows/test.yml@a57add62f2464b6791c594783f513e5194350ac9 # main
    with:
      no-std: false
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@a57add62f2464b6791c594783f513e5194350ac9 # main
    permissions:
      security-events: write # for github/codeql-action/*
